{
 "title": "Nginx VTS Leaddist",
 "description": "Show stats from the hnlq715/nginx-vts-exporter.",
 "tags": [
  "prometheus",
  "nginx"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(nginx_vts_server_bytes_total, instance) "
   },
   {
    "name": "Host",
    "query": "label_values(nginx_vts_server_requests_total{instance=~\"$Instance\"}, host)"
   },
   {
    "name": "Upstream",
    "query": "label_values(nginx_vts_upstream_request_seconds{instance=~\"$Instance\"}, backend)"
   },
   {
    "name": "Code",
    "query": "label_values(nginx_vts_upstream_requests_total{instance=~\"$Instance\"}, code)"
   }
  ]
 },
 "panels": [
  {
   "title": "NGINX TOTAL REQUESTS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_vts_server_requests_total{instance=~\"$Instance\", host=\"$Host\",code=\"total\"}"
    }
   ]
  },
  {
   "title": "HTTP 1xx (Information responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_vts_server_requests_total{instance=~\"$Instance\", host=\"$Host\",code=\"1xx\"}"
    }
   ]
  },
  {
   "title": "HTTP 2xx (Successful responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_vts_server_requests_total{instance=~\"$Instance\", host=\"$Host\",code=\"2xx\"}"
    }
   ]
  },
  {
   "title": "HTTP 3xx (Redirection messages)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_vts_server_requests_total{instance=~\"$Instance\", host=\"$Host\",code=\"3xx\"}"
    }
   ]
  },
  {
   "title": "HTTP 4xx (Client error responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_vts_server_requests_total{instance=~\"$Instance\", host=\"$Host\",code=\"4xx\"}"
    }
   ]
  },
  {
   "title": "HTTP 5xx (Server error responses)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nginx_vts_server_requests_total{instance=~\"$Instance\", host=\"$Host\",code=\"5xx\"}"
    }
   ]
  },
  { "title": "All Domain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "HTTP by Domain",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short", "label": "Total Requests" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_vts_server_requests_total{instance=~\"$Instance\", host!=\"*\", code!=\"total\", code=~\"$Code\"}[1m]) * 50",
     "legendFormat": "{{host}} {{code}}"
    }
   ]
  },
  {
   "title": "HTTP 400 TOTAL",
   "type": "graph",
   "description": "The requests counter  (cumulative)\n{{code: 400 }} TOTAL",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nginx_vts_server_requests_total{code=\"4xx\",instance=~\"$Instance\"}",
     "legendFormat": "{{host}}: {{code}} "
    }
   ]
  },
  {
   "title": "HTTP CODE 400 Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_vts_server_requests_total{instance=~\"$Instance\", code=\"4xx\",host!=\"*\", job=\"nginx_vts\"}[1m])*50",
     "legendFormat": "400 {{host}}"
    }
   ]
  },
  {
   "title": "For Host $Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "Host",
   "collapsed": true,
   "panels": [
    {
     "title": "Server Requests (Response Code) Total",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Requests" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_server_requests_total{instance=~\"$Instance\", host=\"$Host\"}",
       "legendFormat": "{{host}} {{ code }} "
      }
     ]
    },
    {
     "title": "Server Requests (Response Code) RATE",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short", "label": "Requests" }
     ],
     "targets": [
      {
       "expr": "rate(nginx_vts_server_requests_total{instance=~\"$Instance\", host=\"$Host\", code!=\"total\"}[1m]) * 50",
       "legendFormat": "{{host}} {{ code }}"
      }
     ]
    },
    {
     "title": "Nginx Connections Status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_main_connections{instance=~\"$Instance\", status=~\"active|writing|reading|waiting\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Response times ",
     "type": "graph",
     "description": "The request processing time in seconds",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_server_request_seconds{instance=~\"$Instance\"}",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Traffic",
     "type": "graph",
     "description": "The request/response bytes",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_server_bytes_total{instance=~\"$Instance\", host=\"$Host\"}[5m])) by (direction)",
       "legendFormat": "{{ direction }}"
      }
     ]
    },
    {
     "title": "Server Cache",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_server_cache_total{instance=~\"$Instance\", host=\"$Host\"}[5m])) by (status)",
       "legendFormat": "{{ status }}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "For $Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "Upstream",
   "collapsed": true,
   "panels": [
    {
     "title": "UPSTREAM Requests (Response Code) Total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Requests" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_upstream_requests_total{instance=~\"$Instance\", code!=\"total\", code=~\"$Code\", backend=~\"$Upstream\"}",
       "legendFormat": "{{backend}}:{{ code }}"
      }
     ]
    },
    {
     "title": "Upstream Requests Rate",
     "type": "graph",
     "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", backend=~\"^$Upstream\",code!=\"total\", code=~\"$Code\"}[1m]) * 50\n",
       "legendFormat": " {{ backend }} {{ code }}"
      }
     ]
    },
    {
     "title": "UPSTREAM 400 TOTAL",
     "type": "graph",
     "description": "The requests counter  (cumulative)\n{{code: 400 }} TOTAL",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_upstream_requests_total{code=\"4xx\",instance=~\"$Instance\", backend=~\"$Upstream\"}",
       "legendFormat": "{{backend}}: {{code}} "
      }
     ]
    },
    {
     "title": "Upstream Requests 400 Rate",
     "type": "graph",
     "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", backend=~\"^$Upstream\",code!=\"total\", code=~\"4xx\"}[5m])) by (code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "Upstream Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_upstream_bytes_total{instance=~\"$Instance\", backend=~\"^$Upstream$\"}[5m])) by (direction)",
       "legendFormat": "{{ direction }}"
      }
     ]
    },
    {
     "title": "Upstream Backend Response",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nginx_vts_upstream_response_seconds{instance=~\"$Instance\", backend=~\"^$Upstream$\"}) by (backend)",
       "legendFormat": "{{ backend }}"
      }
     ]
    }
   ]
  },
  {
   "title": "For $Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPSTREAM Requests (Response Code) Total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Requests" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_upstream_requests_total{instance=~\"$Instance\", code!=\"total\", code=~\"$Code\", backend=~\"$Upstream\"}",
       "legendFormat": "{{backend}}:{{ code }}"
      }
     ]
    },
    {
     "title": "Upstream Requests Rate",
     "type": "graph",
     "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", backend=~\"^$Upstream\",code!=\"total\", code=~\"$Code\"}[1m]) * 50\n",
       "legendFormat": " {{ backend }} {{ code }}"
      }
     ]
    },
    {
     "title": "UPSTREAM 400 TOTAL",
     "type": "graph",
     "description": "The requests counter  (cumulative)\n{{code: 400 }} TOTAL",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_upstream_requests_total{code=\"4xx\",instance=~\"$Instance\", backend=~\"$Upstream\"}",
       "legendFormat": "{{backend}}: {{code}} "
      }
     ]
    },
    {
     "title": "Upstream Requests 400 Rate",
     "type": "graph",
     "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", backend=~\"^$Upstream\",code!=\"total\", code=~\"4xx\"}[5m])) by (code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "Upstream Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_upstream_bytes_total{instance=~\"$Instance\", backend=~\"^$Upstream$\"}[5m])) by (direction)",
       "legendFormat": "{{ direction }}"
      }
     ]
    },
    {
     "title": "Upstream Backend Response",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nginx_vts_upstream_response_seconds{instance=~\"$Instance\", backend=~\"^$Upstream$\"}) by (backend)",
       "legendFormat": "{{ backend }}"
      }
     ]
    }
   ]
  },
  {
   "title": "For $Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPSTREAM Requests (Response Code) Total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Requests" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_upstream_requests_total{instance=~\"$Instance\", code!=\"total\", code=~\"$Code\", backend=~\"$Upstream\"}",
       "legendFormat": "{{backend}}:{{ code }}"
      }
     ]
    },
    {
     "title": "Upstream Requests Rate",
     "type": "graph",
     "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", backend=~\"^$Upstream\",code!=\"total\", code=~\"$Code\"}[1m]) * 50\n",
       "legendFormat": " {{ backend }} {{ code }}"
      }
     ]
    },
    {
     "title": "UPSTREAM 400 TOTAL",
     "type": "graph",
     "description": "The requests counter  (cumulative)\n{{code: 400 }} TOTAL",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_upstream_requests_total{code=\"4xx\",instance=~\"$Instance\", backend=~\"$Upstream\"}",
       "legendFormat": "{{backend}}: {{code}} "
      }
     ]
    },
    {
     "title": "Upstream Requests 400 Rate",
     "type": "graph",
     "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", backend=~\"^$Upstream\",code!=\"total\", code=~\"4xx\"}[5m])) by (code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "Upstream Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_upstream_bytes_total{instance=~\"$Instance\", backend=~\"^$Upstream$\"}[5m])) by (direction)",
       "legendFormat": "{{ direction }}"
      }
     ]
    },
    {
     "title": "Upstream Backend Response",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nginx_vts_upstream_response_seconds{instance=~\"$Instance\", backend=~\"^$Upstream$\"}) by (backend)",
       "legendFormat": "{{ backend }}"
      }
     ]
    }
   ]
  },
  {
   "title": "For $Upstream",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPSTREAM Requests (Response Code) Total",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short", "label": "Requests" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_upstream_requests_total{instance=~\"$Instance\", code!=\"total\", code=~\"$Code\", backend=~\"$Upstream\"}",
       "legendFormat": "{{backend}}:{{ code }}"
      }
     ]
    },
    {
     "title": "Upstream Requests Rate",
     "type": "graph",
     "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", backend=~\"^$Upstream\",code!=\"total\", code=~\"$Code\"}[1m]) * 50\n",
       "legendFormat": " {{ backend }} {{ code }}"
      }
     ]
    },
    {
     "title": "UPSTREAM 400 TOTAL",
     "type": "graph",
     "description": "The requests counter  (cumulative)\n{{code: 400 }} TOTAL",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "nginx_vts_upstream_requests_total{code=\"4xx\",instance=~\"$Instance\", backend=~\"$Upstream\"}",
       "legendFormat": "{{backend}}: {{code}} "
      }
     ]
    },
    {
     "title": "Upstream Requests 400 Rate",
     "type": "graph",
     "description": "This one is providing aggregated error codes, but it's still possible to graph these per upstream.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_upstream_requests_total{instance=~\"$Instance\", backend=~\"^$Upstream\",code!=\"total\", code=~\"4xx\"}[5m])) by (code)",
       "legendFormat": "{{ code }}"
      }
     ]
    },
    {
     "title": "Upstream Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(nginx_vts_upstream_bytes_total{instance=~\"$Instance\", backend=~\"^$Upstream$\"}[5m])) by (direction)",
       "legendFormat": "{{ direction }}"
      }
     ]
    },
    {
     "title": "Upstream Backend Response",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(nginx_vts_upstream_response_seconds{instance=~\"$Instance\", backend=~\"^$Upstream$\"}) by (backend)",
       "legendFormat": "{{ backend }}"
      }
     ]
    }
   ]
  }
 ]
}